stages:
  - build
  - deploy
build:
  environment:
    name: Build
  only:
    - master
  stage: build
  script:
    - git submodule update --init --recursive
    - cd ./web && get checkout master && git pull && cd ..
    - cd ./syncing-server && git checkout master && git pull && cd ..
    - COMPOSE_PROJECT_NAME=standardnotes docker-compose build
deploy:
  environment:
    name: Deploy to Production
  only:
    - master
  stage: deploy
  script:
    - COMPOSE_PROJECT_NAME=standardnotes docker-compose up -d

