stages:
  - build
  - deploy
build:
  environment:
    name: Build
  only:
    - master
  stage: build
  script:
    - git submodule update --init --recursive
    - git --git-dir ./web/.git pull origin main
    - npm install --prefix ./web/public/extensions/batch-manager
    - npm install --prefix ./web/public/extensions/extensions-manager
    - COMPOSE_PROJECT_NAME=standardnotes docker-compose build
deploy:
  environment:
    name: Deploy to Production
  only:
    - master
  stage: deploy
  script:
    - COMPOSE_PROJECT_NAME=standardnotes docker-compose up -d

